name: Atividade 4 #push, a cada hora uma ação, utilizar uma action pré-existente e pelo menos um script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Agendado para executar a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out do código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '
