name: atividade 4 #push, a cada hora uma ação , utilizar uma action pré existente e pelo menos um script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Agendado para executar a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check-out do código
      uses: actions/checkout@v2
      
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        
    - name: Instalar dependências
      run: npm install
      
    - name: Executar testes
      run: npm test

    - name: Construir aplicação
      run: npm run build
      
    - name: Deploy para ambiente de produção
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production environment..."
        # Comandos para implantar a aplicação no ambiente de produção

    - name: Notificar resultado do build
      if: always()
      run: echo "Build concluído: ${{ job.status }}"

    - name: Rodar script
      run: |
        chmod +x ./scripts/test.sh  # Dá permissão de execução ao script de teste
        ./scripts/test.sh  # Executa o script de teste